Initialisation of a matrix

In [5]:
import numpy as np
A=np.array([[2,4,5],[3,2,-1],[1,-3,1]],dtype=float)
B=np.array([-15,-21,18])
n=3
A=np.reshape(A,(n,n))
B=np.reshape(B,(n,1)) 
print(A)
print(B)

[[ 2.  4.  5.]
 [ 3.  2. -1.]
 [ 1. -3.  1.]]
[[-15]
 [-21]
 [ 18]]


Converting the matrix into triangular matrix

In [6]:
for x in range(0,n) :
  print(A[x])
  B[x]=B[x]/A[x][x]
  A[x]=A[x]/A[x][x]
  print(A)
  print(B)
  print(x)
  print("============")
  for y in range(0,n) :
    if (y==x) :
      continue
    B[y]=B[y]-(B[x]*A[y][x])
    A[y]=A[y]-(A[x]*A[y][x])

[2. 4. 5.]
[[ 1.   2.   2.5]
 [ 3.   2.  -1. ]
 [ 1.  -3.   1. ]]
[[ -7]
 [-21]
 [ 18]]
0
[ 0.  -4.  -8.5]
[[ 1.     2.     2.5  ]
 [-0.     1.     2.125]
 [ 0.    -5.    -1.5  ]]
[[-7]
 [ 0]
 [25]]
1
[0.    0.    9.125]
[[ 1.     0.    -1.75 ]
 [-0.     1.     2.125]
 [ 0.     0.     1.   ]]
[[-7]
 [ 0]
 [ 2]]
2
